#ifndef _GAME_COMMON_H_H_
#define _GAME_COMMON_H_H_

// 枚举:游戏层
enum ENUM_GAME_LAYER
{
	LAYER_BACKGROUND_1,
	LAYER_BACKGROUND_2,
	LAYER_BACKGROUND_3,
	LAYER_GROUND_1,
	LAYER_GROUND_2,
	LAYER_GROUND_3,
	LAYER_SKY_UNDER_1,
	LAYER_SKY_UNDER_2,
	LAYER_SKY_UNDER_3,
	LAYER_PLAYER_BULLET,
	LAYER_ENEMY_BULLET,
	LAYER_ENEMY_1,
	LAYER_ENEMY_2,
	LAYER_ENEMY_3,
	LAYER_ENEMY_BOOM,
	LAYER_PLAYER,
	LAYER_PLAYER_BOOM,
	LAYER_ITEM,
	LAYER_SKY_TOP_1,
	LAYER_SKY_TOP_2,
	LAYER_SKY_TOP_3,
	LAYER_UI_1,
	LAYER_UI_2,
	LAYER_UI_3,
};

#endif